# Generated by Django 3.1.5 on 2021-01-15 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type1', models.CharField(max_length=150)),
                ('type2', models.CharField(max_length=150)),
                ('publish_date', models.DateField(max_length=150)),
                ('start_date', models.DateField(max_length=150)),
                ('end_date', models.DateField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('home_count', models.CharField(max_length=150)),
                ('vote_tk', models.DateField()),
                ('vote_1', models.DateField()),
                ('vote_2', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplyHomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.apply')),
            ],
        ),
    ]
