# Generated by Django 3.1.5 on 2021-01-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='site',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
