# Generated by Django 3.1.5 on 2021-01-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_apply_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='vote_1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='vote_2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='vote_tk',
            field=models.DateField(null=True),
        ),
    ]
