# Generated by Django 3.1.5 on 2021-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20210115_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='address',
            field=models.CharField(max_length=150, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='home_count',
            field=models.CharField(max_length=150, verbose_name='세대수'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=150, verbose_name='주택명'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='publish_date',
            field=models.DateField(max_length=150, verbose_name='모집공고일'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='site',
            field=models.CharField(max_length=150, verbose_name='도시'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='type1',
            field=models.CharField(max_length=150, verbose_name='주택구분'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='type2',
            field=models.CharField(max_length=150, verbose_name='분양/임대'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='vote_1',
            field=models.DateField(null=True, verbose_name='1순위(해당)'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='vote_2',
            field=models.DateField(null=True, verbose_name='2순위(해당)'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='vote_tk',
            field=models.DateField(null=True, verbose_name='특공(해당)'),
        ),
        migrations.AlterField(
            model_name='applyhometype',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
