# Generated by Django 3.1.5 on 2021-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20210115_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='vote_n',
            field=models.DateField(null=True, verbose_name='무순위'),
        ),
    ]
