# Generated by Django 3.1.5 on 2021-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_apply_vote_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
