# Generated by Django 3.1.5 on 2021-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_apply_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
